# -*- coding: utf-8 -*-
"""MediSnap_Backend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-tfhUR9DWb4T3PQU4HdIrcGlNwnbr_5N

# MediSnap Backend — Colab Notebook
**Runtime 請選 T4 GPU**（上方選單 > Runtime > Change runtime type > T4 GPU）

照順序一個一個執行就好

## Cell 0: 先跑numpy-1.26.4版本，重啟後，從Cell 1 開始跑
"""

!pip uninstall numpy -y 2>/dev/null
!pip install "numpy>=1.24,<2" --force-reinstall --no-deps
print("\n✅ numpy 已降版，請點：執行階段 → 重新啟動工作階段")
print("👉 重啟後從 Cell 1 按「執行儲存格和下方所有儲存格」")

"""## Cell 1：掛載 Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""## Cell 2：確認模型檔案是否存在"""

import os

paths = {
    "MedBERT v5": "/content/drive/MyDrive/MediSnap_files/models/ragllm/medbert-pharma-v5-contrastive",
    "ChromaDB v5": "/content/drive/MyDrive/MediSnap_files/models/ragllm/chromadb_store_v5",
    "YOLO best.pt": "/content/drive/MyDrive/MediSnap_files/models/detection_yolo26/weights/best.pt",
}

all_ok = True
for name, path in paths.items():
    exists = os.path.exists(path)
    status = "✅" if exists else "❌"
    print(f"{status} {name}: {path}")
    if not exists:
        all_ok = False

if all_ok:
    print("\n✅ 所有模型檔案都在！")
else:
    print("\n❌ 有檔案缺失，請檢查 Google Drive")

"""## Cell 3：安裝所有套件（約 2-3 分鐘）"""

import numpy as np
assert int(np.__version__.split('.')[0]) < 2, f"❌ numpy {np.__version__} 是 2.x！請先跑 Cell 0 再重啟 session"
print(f"✅ numpy {np.__version__} OK")

# 安裝所有套件
!pip install -q \
    fastapi==0.115.0 \
    uvicorn==0.30.6 \
    python-multipart==0.0.9 \
    chromadb==0.5.23 \
    torch \
    transformers==4.44.2 \
    "ultralytics>=8.3,<9" \
    pyngrok==7.2.2 \
    nest-asyncio==1.6.0 \
    httpx==0.27.2 \
    "numpy>=1.24,<2"

# 驗證 numpy 沒被蓋掉
import importlib
if 'numpy' in __import__('sys').modules:
    del __import__('sys').modules['numpy']
import numpy as np
assert int(np.__version__.split('.')[0]) < 2, f"❌ numpy 被蓋回 {np.__version__}！"
print(f"✅ 安裝完成，numpy {np.__version__}")

# ── 修復 ChromaDB _type 問題 ──
import sqlite3, json

db_path = "/content/drive/MyDrive/MediSnap_files/models/ragllm/chromadb_store_v5/chroma.sqlite3"
conn = sqlite3.connect(db_path)
cur = conn.cursor()
cur.execute("SELECT id, config_json_str FROM collections")
rows = cur.fetchall()
fixed = 0
for row_id, config_str in rows:
    config = json.loads(config_str) if config_str else {}
    if "_type" not in config:
        config["_type"] = "CollectionConfigurationInternal"
        cur.execute("UPDATE collections SET config_json_str = ? WHERE id = ?",
                    (json.dumps(config), row_id))
        fixed += 1
conn.commit()
conn.close()
if fixed > 0:
    print(f"✅ ChromaDB 已修復（patch 了 {fixed} 個 collection）")
else:
    print("✅ ChromaDB 不需要修復")

"""## Cell 4：安裝並啟動 Ollama"""

!sudo apt-get install -y zstd > /dev/null 2>&1
!curl -fsSL https://ollama.com/install.sh | sh > /dev/null 2>&1

import subprocess, time, requests

# 啟動 Ollama server
subprocess.Popen(['ollama', 'serve'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

for i in range(10):
    time.sleep(5)
    try:
        requests.get("http://localhost:11434/api/tags", timeout=3)
        print(f"✅ Ollama 啟動成功！（等了 {(i+1)*5} 秒）")
        break
    except:
        print(f"⏳ 等待 Ollama...（{(i+1)*5} 秒）")
else:
    print("❌ Ollama 啟動失敗")

"""## Cell 5：下載 qwen2.5:3b 模型（約 2GB，需要幾分鐘）"""

!ollama pull qwen2.5:1.5b

import requests

resp = requests.post(
    "http://localhost:11434/api/generate",
    json={"model": "qwen2.5:1.5b", "prompt": "你好", "stream": False},
    timeout=120
)
print("狀態碼：", resp.status_code)
print("完整回應：", resp.text[:500])

"""## Cell 6：測試 Ollama 回應"""

import requests

try:
    resp = requests.post(
        "http://localhost:11434/api/generate",
        json={"model": "qwen2.5:1.5b", "prompt": "你好", "stream": False},
        timeout=120
    )
    print(f"✅ LLM 回應正常：{resp.json()['response'][:50]}")
except Exception as e:
    print(f"⚠️ LLM 測試失敗：{e}")

"""## Cell 7：建立 inference.py

### GPU >> LLM 跑 Ollama (會跑比較久)
"""

# %%writefile /content/inference.py
# # ===== numpy 版本檢查 =====
# import numpy as np
# assert int(np.__version__.split('.')[0]) < 2, f"❌ numpy {np.__version__} 不相容！"

# import requests
# import chromadb
# import torch
# import torch.nn.functional as F
# from transformers import AutoTokenizer, BertModel
# from ultralytics import YOLO
# from PIL import Image
# import io
# import json

# # ==================== 設定區 ====================
# CHROMA_PATH = "/content/drive/MyDrive/MediSnap_files/models/ragllm/chromadb_store_v5"
# EMBEDDING_MODEL_PATH = "/content/drive/MyDrive/MediSnap_files/models/ragllm/medbert-pharma-v5-contrastive"
# YOLO_MODEL_PATH = "/content/drive/MyDrive/MediSnap_files/models/detection_yolo26/weights/best.pt"

# # ===== Ollama LLM =====
# OLLAMA_URL = "http://localhost:11434/api/generate"
# LLM_MODEL = "qwen2.5:1.5b"
# # ================================================

# YOLO_TO_BRAND = {
#     "Aspirin": "Thromkey Enteric-Microencapsulated Capsules 100mg",
#     "Concor": "Concor 5 / Concor 10",
#     "Eliquis-2.5mg": "Eliquis Film-Coated Tablet 2.5mg",
#     "Esidrex-25mg": "Esidrex 25mg",
#     "Eveness-10mg": "Eveness 10mg",
#     "Fixuric-40mg": "Fixuric 40mg",
#     "Fusix-40mg": "Fusix",
#     "MERCK": "GLUCOPHAGE XR",
#     "Natrilix-1-5mg": "NATRILIX SR",
#     "Panadol Advance": "Panadol film coated caplets 500MG",
#     "Physiotens": "Physiotens",
#     "Plavix-75mg": "Plavix",
#     "Sorbitrate": "Sorbitrate",
#     "Xyzal-5mg": "Xyzal",
#     "Zyloric": "Zyloric",
# }

# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# print(f"使用裝置：{device}")

# print("載入 MedBERT...")
# tokenizer = AutoTokenizer.from_pretrained(EMBEDDING_MODEL_PATH)
# bert_model = BertModel.from_pretrained(EMBEDDING_MODEL_PATH).to(device)
# bert_model.eval()
# print("✅ MedBERT 載入完成")

# print("載入 YOLO...")
# yolo_model = YOLO(YOLO_MODEL_PATH)
# print("✅ YOLO 載入完成")

# print("連接 ChromaDB...")
# chroma_client = chromadb.PersistentClient(path=CHROMA_PATH)
# collection = chroma_client.get_collection("pharma_chunks")
# print(f"✅ ChromaDB 共 {collection.count()} 筆")

# print(f"✅ LLM：Ollama ({LLM_MODEL})")
# print("\n🎉 所有模型載入完成！")


# def get_embedding(text):
#     inputs = tokenizer(
#         text, return_tensors='pt',
#         max_length=256, truncation=True, padding='max_length'
#     ).to(device)
#     with torch.no_grad():
#         outputs = bert_model(**inputs)
#     cls_emb = outputs.last_hidden_state[:, 0, :]
#     cls_emb = F.normalize(cls_emb, p=2, dim=1)
#     return cls_emb.squeeze().cpu().numpy().tolist()


# def detect_drug(image_bytes):
#     try:
#         image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
#         results = yolo_model.predict(image, conf=0.5, verbose=False)
#         if results and len(results[0].boxes) > 0:
#             boxes = results[0].boxes
#             best_idx = boxes.conf.argmax().item()
#             class_id = int(boxes.cls[best_idx].item())
#             class_name = yolo_model.names[class_id]
#             confidence = float(boxes.conf[best_idx].item())
#             return class_name, confidence
#         return "未知藥品", 0.0
#     except Exception as e:
#         print(f"YOLO 辨識錯誤：{e}")
#         return "未知藥品", 0.0

# def find_drug_name(user_input):
#     """判斷使用者輸入是否包含藥名，如果是就回傳匹配的藥名"""
#     text = user_input.strip()

#     for name in YOLO_TO_BRAND:
#         if name.lower() in text.lower():
#             return name

#     try:
#         all_data = collection.get(include=["metadatas"])
#         known_names = set()
#         name_to_drug = {}
#         for meta in all_data["metadatas"]:
#             dn = meta.get("drug_name", "")
#             bn = meta.get("brand_name", "")
#             gn = meta.get("generic_name", "")
#             if dn:
#                 known_names.add(dn)
#                 name_to_drug[dn] = dn
#             if bn:
#                 known_names.add(bn)
#                 name_to_drug[bn] = dn or bn
#             if gn:
#                 known_names.add(gn)
#                 name_to_drug[gn] = dn or bn

#         for name in known_names:
#             if name and len(name) >= 2 and name.lower() in text.lower():
#                 return name_to_drug.get(name, name)
#             if name and len(text) >= 2 and text in name:
#                 return name_to_drug.get(name, name)
#     except Exception as e:
#         print(f"find_drug_name 錯誤：{e}")

#     return None


# def get_all_sections(brand_name=None, search_name=None):
#     """取得該藥品所有 section 的資料"""
#     try:
#         results = None

#         if brand_name:
#             results = collection.get(
#                 where={"brand_name": {"$eq": brand_name}},
#                 include=["documents", "metadatas"]
#             )

#         if (not results or not results["documents"]) and search_name:
#             results = collection.get(
#                 where={"drug_name": {"$eq": search_name}},
#                 include=["documents", "metadatas"]
#             )

#         if (not results or not results["documents"]) and search_name:
#             results = collection.get(
#                 where={"brand_name": {"$eq": search_name.upper()}},
#                 include=["documents", "metadatas"]
#             )

#         sections = {}
#         if results and results["documents"]:
#             for doc, meta in zip(results["documents"], results["metadatas"]):
#                 section = meta.get("section", "其他")
#                 if section not in sections:
#                     sections[section] = {"content": doc, "metadata": meta}
#         return sections
#     except Exception as e:
#         print(f"取得 sections 失敗：{e}")
#         return {}


# def call_llm(system_msg, user_msg):
#     """呼叫 Ollama LLM"""
#     prompt = f"{system_msg}\n\n{user_msg}"
#     try:
#         resp = requests.post(
#             OLLAMA_URL,
#             json={"model": LLM_MODEL, "prompt": prompt, "stream": False},
#             timeout=180
#         )
#         return resp.json()["response"]
#     except Exception as e:
#         print(f"LLM 呼叫失敗：{e}")
#         return None


# def query_rag_llm(drug_name: str, question: str, is_followup: bool = False) -> dict:
#     brand_name = YOLO_TO_BRAND.get(drug_name, None)

#     # 如果長名稱（含 /）查不到，拆開每個部分試
#     if not brand_name and '/' in drug_name:
#         for part in drug_name.split('/'):
#             part = part.strip()
#             if YOLO_TO_BRAND.get(part, None):
#                 brand_name = YOLO_TO_BRAND[part]
#                 break

#     sections = get_all_sections(brand_name=brand_name, search_name=drug_name)

#     # 如果還是查不到，用拆開的名稱再試
#     if not sections and '/' in drug_name:
#         for part in drug_name.split('/'):
#             part = part.strip()
#             sections = get_all_sections(brand_name=part, search_name=part)
#             if sections:
#                 break

#     context_parts = []
#     all_sources = []
#     for section_name, data in sections.items():
#         context_parts.append(f"【{section_name}】\n{data['content']}")
#         all_sources.append(data['metadata'])

#     if not context_parts:
#         embedding = get_embedding(f"{drug_name} {question}")
#         results = collection.query(
#             query_embeddings=[embedding],
#             n_results=5
#         )
#         context_parts = [f"【{m.get('section','未知')}】\n{d}"
#                         for d, m in zip(results["documents"][0], results["metadatas"][0])]
#         all_sources = results["metadatas"][0]

#     context = "\n\n".join(context_parts)

#     display_name = drug_name
#     if all_sources:
#         cn_name = all_sources[0].get('drug_name', '')
#         brand = all_sources[0].get('brand_name', '')
#         generic = all_sources[0].get('generic_name', '')
#         parts = []
#         if cn_name:
#             parts.append(cn_name)
#         if brand:
#             parts.append(brand)
#         if generic:
#             parts.append(generic)
#         if parts:
#             display_name = " / ".join(parts)

#     # ===== 根據是首次辨識還是追問，用不同的 prompt =====
#     system_msg = "你是一個專業的藥品衛教助手。請務必使用繁體中文回答。只能根據參考資料回答，不可編造。回答時請優先使用民眾常用的藥品名稱（如阿斯匹靈、普拿疼、保栓通等），再附上正式品牌名與學名，格式例如：「阿斯匹靈（Aspirin），正式品牌名：伏栓腸溶微粒膠囊 100 毫克」。如果參考資料中沒有相關資訊，請回答「根據現有資料未提及此部分，建議您諮詢醫師或藥師以獲得更完整的資訊。」如果使用者的問題跟藥品完全無關（例如天氣、聊天、數學等），請回答「我是藥品衛教助手，請問跟藥品相關的問題喔 😊」，不要嘗試回答無關問題。"

#     if is_followup:
#         user_msg = f"""藥品名稱：{display_name}

# 參考資料：
# {context}

# 使用者問題：{question}

# 請仔細閱讀以上所有參考資料（包含適應症、用法用量、副作用、禁忌症、警語、交互作用等所有 section），然後針對使用者的問題回答。
# 回答要簡潔清楚，用一般人能理解的語言。
# 如果答案在任何一個 section 裡有提到，請務必引用該內容回答。
# 不要列出所有 section，只回答跟問題相關的內容。不需要加免責聲明。"""
#     else:
#         user_msg = f"""藥品名稱：{display_name}

# 參考資料：
# {context}

# 使用者問題：{question}

# 請先用一行顯示完整藥品名稱，然後用以下格式回答（每段精簡摘要，不超過 100 字）：
# 藥品：{display_name}

# 【適應症】（簡述用途）
# 【用法用量】（簡述劑量和服用方式）
# 【常見副作用】（列出主要副作用）
# 【禁忌症】（列出不能使用的情況）
# 【警語】（列出重要警告）

# 不需要加免責聲明。"""

#     answer = call_llm(system_msg, user_msg)

#     # Fallback
#     if not answer:
#         answer = ""
#         for section_name, data in sections.items():
#             answer += f"【{section_name}】\n{data['content'][:150]}\n\n"
#         if not answer:
#             answer = "暫時無法取得藥品資訊，請稍後再試。"

#     return {"drug_name": display_name, "answer": answer, "sources": all_sources}

"""### 沒有GPU時，使用groq LLM (處理速度快且穩定，適合 LLM 的連續性計算，不需使用複雜的並行技術。)"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/inference.py
# # ===== numpy 版本檢查 =====
# import numpy as np
# assert int(np.__version__.split('.')[0]) < 2, f"❌ numpy {np.__version__} 不相容！"
# 
# import requests
# import chromadb
# import torch
# import torch.nn.functional as F
# from transformers import AutoTokenizer, BertModel
# from ultralytics import YOLO
# from PIL import Image
# import io
# import json
# 
# # ==================== 設定區 ====================
# CHROMA_PATH = "/content/drive/MyDrive/MediSnap_files/models/ragllm/chromadb_store_v5"
# EMBEDDING_MODEL_PATH = "/content/drive/MyDrive/MediSnap_files/models/ragllm/medbert-pharma-v5-contrastive"
# YOLO_MODEL_PATH = "/content/drive/MyDrive/MediSnap_files/models/detection_yolo26/weights/best.pt"
# 
# # ===== Groq API =====
# GROQ_API_KEY = "YOUR_GROQ_API_KEY"  # 請到 https://console.groq.com 取得
# GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"
# GROQ_MODEL = "llama-3.1-8b-instant"
# # ================================================
# 
# YOLO_TO_BRAND = {
#     "Aspirin": "Thromkey Enteric-Microencapsulated Capsules 100mg",
#     "Concor": "Concor 5 / Concor 10",
#     "Eliquis-2.5mg": "Eliquis Film-Coated Tablet 2.5mg",
#     "Esidrex-25mg": "Esidrex 25mg",
#     "Eveness-10mg": "Eveness 10mg",
#     "Fixuric-40mg": "Fixuric 40mg",
#     "Fusix-40mg": "Fusix",
#     "MERCK": "GLUCOPHAGE XR",
#     "Natrilix-1-5mg": "NATRILIX SR",
#     "Panadol Advance": "Panadol film coated caplets 500MG",
#     "Physiotens": "Physiotens",
#     "Plavix-75mg": "Plavix",
#     "Sorbitrate": "Sorbitrate",
#     "Xyzal-5mg": "Xyzal",
#     "Zyloric": "Zyloric",
# }
# 
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# print(f"使用裝置：{device}")
# 
# print("載入 MedBERT...")
# tokenizer = AutoTokenizer.from_pretrained(EMBEDDING_MODEL_PATH)
# bert_model = BertModel.from_pretrained(EMBEDDING_MODEL_PATH).to(device)
# bert_model.eval()
# print("✅ MedBERT 載入完成")
# 
# print("載入 YOLO...")
# yolo_model = YOLO(YOLO_MODEL_PATH)
# print("✅ YOLO 載入完成")
# 
# print("連接 ChromaDB...")
# chroma_client = chromadb.PersistentClient(path=CHROMA_PATH)
# collection = chroma_client.get_collection("pharma_chunks")
# print(f"✅ ChromaDB 共 {collection.count()} 筆")
# 
# print(f"✅ LLM：Groq API ({GROQ_MODEL})")
# print("\n🎉 所有模型載入完成！")
# 
# 
# def get_embedding(text):
#     inputs = tokenizer(
#         text, return_tensors='pt',
#         max_length=256, truncation=True, padding='max_length'
#     ).to(device)
#     with torch.no_grad():
#         outputs = bert_model(**inputs)
#     cls_emb = outputs.last_hidden_state[:, 0, :]
#     cls_emb = F.normalize(cls_emb, p=2, dim=1)
#     return cls_emb.squeeze().cpu().numpy().tolist()
# 
# 
# def detect_drug(image_bytes):
#     try:
#         image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
#         results = yolo_model.predict(image, conf=0.5, verbose=False)
#         if results and len(results[0].boxes) > 0:
#             boxes = results[0].boxes
#             best_idx = boxes.conf.argmax().item()
#             class_id = int(boxes.cls[best_idx].item())
#             class_name = yolo_model.names[class_id]
#             confidence = float(boxes.conf[best_idx].item())
#             return class_name, confidence
#         return "未知藥品", 0.0
#     except Exception as e:
#         print(f"YOLO 辨識錯誤：{e}")
#         return "未知藥品", 0.0
# 
# def find_drug_name(user_input):
#     """判斷使用者輸入是否包含藥名，如果是就回傳匹配的藥名"""
#     text = user_input.strip()
# 
#     # 1. 先查 YOLO_TO_BRAND 的 key（英文名）
#     for name in YOLO_TO_BRAND:
#         if name.lower() in text.lower():
#             return name
# 
#     # 2. 查 ChromaDB 裡所有 drug_name（中文名）和 brand_name
#     try:
#         all_data = collection.get(include=["metadatas"])
#         known_names = set()
#         name_to_drug = {}
#         for meta in all_data["metadatas"]:
#             dn = meta.get("drug_name", "")
#             bn = meta.get("brand_name", "")
#             gn = meta.get("generic_name", "")
#             if dn:
#                 known_names.add(dn)
#                 name_to_drug[dn] = dn
#             if bn:
#                 known_names.add(bn)
#                 name_to_drug[bn] = dn or bn
#             if gn:
#                 known_names.add(gn)
#                 name_to_drug[gn] = dn or bn
# 
#         for name in known_names:
#             if name and len(name) >= 2 and name.lower() in text.lower():
#                 return name_to_drug.get(name, name)
#             if name and len(text) >= 2 and text in name:
#                 return name_to_drug.get(name, name)
#     except Exception as e:
#         print(f"find_drug_name 錯誤：{e}")
# 
#     return None
# 
# 
# 
# def get_all_sections(brand_name=None, search_name=None):
#     """取得該藥品所有 section 的資料"""
#     try:
#         results = None
# 
#         # 先用 brand_name 查
#         if brand_name:
#             results = collection.get(
#                 where={"brand_name": {"$eq": brand_name}},
#                 include=["documents", "metadatas"]
#             )
# 
#         # 如果沒查到，用 drug_name 查（支援中文藥名）
#         if (not results or not results["documents"]) and search_name:
#             results = collection.get(
#                 where={"drug_name": {"$eq": search_name}},
#                 include=["documents", "metadatas"]
#             )
# 
#         # 如果還是沒查到，用 brand_name 欄位模糊查（大小寫）
#         if (not results or not results["documents"]) and search_name:
#             results = collection.get(
#                 where={"brand_name": {"$eq": search_name.upper()}},
#                 include=["documents", "metadatas"]
#             )
# 
#         sections = {}
#         if results and results["documents"]:
#             for doc, meta in zip(results["documents"], results["metadatas"]):
#                 section = meta.get("section", "其他")
#                 if section not in sections:
#                     sections[section] = {"content": doc, "metadata": meta}
#         return sections
#     except Exception as e:
#         print(f"取得 sections 失敗：{e}")
#         return {}
# 
# 
# def call_groq(system_msg, user_msg):
#     """呼叫 Groq API"""
#     try:
#         resp = requests.post(
#             GROQ_URL,
#             headers={
#                 "Authorization": f"Bearer {GROQ_API_KEY}",
#                 "Content-Type": "application/json"
#             },
#             json={
#                 "model": GROQ_MODEL,
#                 "messages": [
#                     {"role": "system", "content": system_msg},
#                     {"role": "user", "content": user_msg}
#                 ],
#                 "temperature": 0.3,
#                 "max_tokens": 1500
#             },
#             timeout=30
#         )
#         data = resp.json()
#         return data["choices"][0]["message"]["content"]
#     except Exception as e:
#         print(f"Groq API 錯誤：{e}")
#         return None
# 
# 
# def query_rag_llm(drug_name: str, question: str, is_followup: bool = False) -> dict:
#     brand_name = YOLO_TO_BRAND.get(drug_name, None)
# 
#     # 如果長名稱（含 /）查不到，拆開每個部分試
#     if not brand_name and '/' in drug_name:
#         for part in drug_name.split('/'):
#             part = part.strip()
#             if YOLO_TO_BRAND.get(part, None):
#                 brand_name = YOLO_TO_BRAND[part]
#                 break
# 
#     # 用 brand_name 和 drug_name 兩種方式查
#     sections = get_all_sections(brand_name=brand_name, search_name=drug_name)
# 
#     # 如果還是查不到，用拆開的名稱再試
#     if not sections and '/' in drug_name:
#         for part in drug_name.split('/'):
#             part = part.strip()
#             sections = get_all_sections(brand_name=part, search_name=part)
#             if sections:
#                 break
# 
#     context_parts = []
#     all_sources = []
#     for section_name, data in sections.items():
#         context_parts.append(f"【{section_name}】\n{data['content']}")
#         all_sources.append(data['metadata'])
# 
#     if not context_parts:
#         embedding = get_embedding(f"{drug_name} {question}")
#         results = collection.query(
#             query_embeddings=[embedding],
#             n_results=5
#         )
#         context_parts = [f"【{m.get('section','未知')}】\n{d}"
#                         for d, m in zip(results["documents"][0], results["metadatas"][0])]
#         all_sources = results["metadatas"][0]
# 
#     context = "\n\n".join(context_parts)
# 
#     display_name = drug_name
#     if all_sources:
#         cn_name = all_sources[0].get('drug_name', '')
#         brand = all_sources[0].get('brand_name', '')
#         generic = all_sources[0].get('generic_name', '')
#         parts = []
#         if cn_name:
#             parts.append(cn_name)
#         if brand:
#             parts.append(brand)
#         if generic:
#             parts.append(generic)
#         if parts:
#             display_name = " / ".join(parts)
# 
#     # ===== 根據是首次辨識還是追問，用不同的 prompt =====
#     system_msg = "你是一個專業的藥品衛教助手。請務必使用繁體中文回答。只能根據參考資料回答，不可編造。回答時請優先使用民眾常用的藥品名稱（如阿斯匹靈、普拿疼、保栓通等），再附上正式品牌名與學名，格式例如：「阿斯匹靈（Aspirin），正式品牌名：伏栓腸溶微粒膠囊 100 毫克」。如果參考資料中沒有相關資訊，請回答「根據現有資料未提及此部分，建議您諮詢醫師或藥師以獲得更完整的資訊。」如果使用者的問題跟藥品完全無關（例如天氣、聊天、數學等），請回答「我是藥品衛教助手，請問跟藥品相關的問題喔 😊」，不要嘗試回答無關問題。"
# 
#     if is_followup:
#         # ── 追問模式：只針對使用者的問題回答 ──
#         user_msg = f"""藥品名稱：{display_name}
# 
# 參考資料：
# {context}
# 
# 使用者問題：{question}
# 
# 請仔細閱讀以上所有參考資料（包含適應症、用法用量、副作用、禁忌症、警語、交互作用等所有 section），然後針對使用者的問題回答。
# 回答要簡潔清楚，用一般人能理解的語言。
# 如果答案在任何一個 section 裡有提到，請務必引用該內容回答。
# 不要列出所有 section，只回答跟問題相關的內容。不需要加免責聲明。"""
#     else:
#         # ── 首次辨識模式：列出完整衛教資訊 ──
#         user_msg = f"""藥品名稱：{display_name}
# 
# 參考資料：
# {context}
# 
# 使用者問題：{question}
# 
# 請先用一行顯示完整藥品名稱，然後用以下格式回答（每段精簡摘要，不超過 100 字）：
# 藥品：{display_name}
# 
# 【適應症】（簡述用途）
# 【用法用量】（簡述劑量和服用方式）
# 【常見副作用】（列出主要副作用）
# 【禁忌症】（列出不能使用的情況）
# 【警語】（列出重要警告）
# 
# 不需要加免責聲明。"""
# 
#     answer = call_groq(system_msg, user_msg)
# 
#     # Fallback
#     if not answer:
#         answer = ""
#         for section_name, data in sections.items():
#             answer += f"【{section_name}】\n{data['content'][:150]}\n\n"
#         if not answer:
#             answer = "暫時無法取得藥品資訊，請稍後再試。"
# 
#     return {"drug_name": display_name, "answer": answer, "sources": all_sources}

"""## Cell 8：建立 main.py"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/main.py
# 
# from fastapi import FastAPI, UploadFile, File, Form
# from fastapi.middleware.cors import CORSMiddleware
# from fastapi.responses import HTMLResponse
# from inference import query_rag_llm, detect_drug, collection
# import json
# import os
# 
# app = FastAPI(title="MediSnap API")
# 
# app.add_middleware(
#     CORSMiddleware,
#     allow_origins=["*"],
#     allow_methods=["*"],
#     allow_headers=["*"],
# )
# 
# @app.get("/", response_class=HTMLResponse)
# async def serve_web_app():
#     web_path = "/content/medisnap_web.html"
#     if os.path.exists(web_path):
#         with open(web_path, "r", encoding="utf-8") as f:
#             return HTMLResponse(content=f.read())
#     return HTMLResponse(content="<h1>MediSnap Web App not found</h1>")
# 
# @app.get("/health")
# async def health_check():
#     return {"status": "ok", "message": "MediSnap API is running on Colab"}
# 
# @app.post("/analyze")
# async def analyze_pill(
#     image: UploadFile = File(...),
#     question: str = Form(default="這顆藥是什麼？有什麼副作用和注意事項？")
# ):
#     image_bytes = await image.read()
#     drug_name, confidence = detect_drug(image_bytes)
# 
#     if drug_name == "未知藥品" or confidence < 0.5:
#         return {
#             "drug_name": "無法辨識",
#             "confidence": confidence,
#             "answer": "很抱歉，系統無法辨識這顆藥品。請重新拍攝或諮詢藥師。",
#             "citation": "[]",
#             "warning": "本系統僅供參考，無法辨識時請諮詢專業藥師"
#         }
# 
#     result = query_rag_llm(drug_name, question, is_followup=False)
#     return {
#         "drug_name": result["drug_name"],
#         "confidence": confidence,
#         "answer": result["answer"],
#         "citation": json.dumps(result["sources"], ensure_ascii=False),
#         "warning": "本資訊非診斷，請諮詢專業人員"
#     }
# 
# @app.post("/chat")
# async def chat_with_ai(
#     drug_name: str = Form(...),
#     question: str = Form(...),
#     is_followup: str = Form(default="true")
# ):
#     print(f"📡 /chat 收到: drug_name='{drug_name}', question='{question}', is_followup='{is_followup}'")
#     followup = is_followup.lower() in ("true", "1", "yes")
#     result = query_rag_llm(drug_name, question, is_followup=followup)
#     return {
#         "drug_name": result["drug_name"],
#         "answer": result["answer"],
#         "citation": json.dumps(result["sources"], ensure_ascii=False),
#         "warning": "本資訊非診斷，請諮詢專業人員"
#     }
# 
# @app.post("/search")
# async def search_drug(
#     keyword: str = Form(...)
# ):
#     if len(keyword.strip()) < 2:
#         return {"results": []}
#     text = keyword.strip()
#     try:
#         all_data = collection.get(include=["metadatas"])
#         seen = set()
#         results = []
#         for meta in all_data["metadatas"]:
#             dn = meta.get("drug_name", "")
#             bn = meta.get("brand_name", "")
#             gn = meta.get("generic_name", "")
#             if (text in dn or text in bn or text.lower() in bn.lower()
#                 or text in gn or text.lower() in gn.lower()):
#                 key = f"{dn}|{bn}|{gn}"
#                 if key not in seen:
#                     seen.add(key)
#                     results.append({
#                         "drug_name": dn,
#                         "brand_name": bn,
#                         "generic_name": gn,
#                         "display": " / ".join(filter(None, [dn, bn, gn]))
#                     })
#         return {"results": results}
#     except Exception as e:
#         return {"results": [], "error": str(e)}

!cp "/content/drive/MyDrive/MediSnap_files/medisnap_web.html" /content/medisnap_web.html
print("✅ 網頁版已部署")

"""## Cell 9：設定 ngrok + 啟動伺服器
### ⚠️ 請先到 https://ngrok.com 免費註冊，取得 authtoken
"""

!pkill ngrok
import time
time.sleep(2)
print("✅ 已清除舊的 ngrok")

import subprocess, time, requests, nest_asyncio
from pyngrok import ngrok

nest_asyncio.apply()

# ===== 殺掉舊的 =====
subprocess.run(['pkill', '-f', 'uvicorn'], capture_output=True)
time.sleep(3)

# ===== ngrok =====
NGROK_TOKEN = "YOUR_NGROK_TOKEN"  # 請到 https://ngrok.com 註冊取得  # ← 換成你的

ngrok.set_auth_token(NGROK_TOKEN)
ngrok.kill()
time.sleep(2)

public_url = ngrok.connect(8000)
url_str = str(public_url).split('"')[1] if '"' in str(public_url) else str(public_url)

# ===== 啟動 FastAPI =====
subprocess.Popen(
    ["python", "-c", "import uvicorn; uvicorn.run('main:app', host='0.0.0.0', port=8000)"],
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT
)

# ===== 等待啟動 =====
print("⏳ 等待 FastAPI 啟動...")
for i in range(18):
    time.sleep(10)
    try:
        r = requests.get("http://localhost:8000/health", timeout=5)
        print(f"\n✅ FastAPI 啟動成功！")
        break
    except:
        print(f"  ⏳ 已等 {(i+1)*10} 秒...")
else:
    print("\n❌ 啟動失敗")

# ===== 顯示結果 =====
print("\n" + "=" * 60)
print(f"🌐 公開 URL：{url_str}")
print(f"📱 baseURL：{url_str}")
print(f"🧪 測試：{url_str}/health")
print("=" * 60)

import requests

# 1. 檢查 FastAPI 是否在跑
try:
    r = requests.get("http://localhost:8000/health", timeout=5)
    print(f"✅ FastAPI 在跑：{r.json()}")
except Exception as e:
    print(f"❌ FastAPI 沒在跑：{e}")

# 2. 檢查 Ollama 是否在跑
try:
    r = requests.get("http://localhost:11434/api/tags", timeout=5)
    print(f"✅ Ollama 在跑：{r.json()}")
except Exception as e:
    print(f"❌ Ollama 沒在跑：{e}")

import requests
r = requests.get("http://localhost:8000/health", timeout=5)
print(r.json())